SELECT * FROM interior.`interiors.csv`;
Select * from interior.`interiors.csv` where TYPE='SOFA';
Select `ITEM NAME` from interior.`interiors.csv` where PRICE>10000;
Select `ITEM NAME`,`TYPE` from interior.`interiors.csv` where `DATE OF STOCK`<'22-01-2002' ORDER BY `ITEM NAME` DESC;
Select `ITEM NAME`,`DATE OF STOCK` from interior.`interiors.csv` where discount>15;
Select Count(*) from interior.`interiors.csv` where TYPE='Double Bed';
Insert into interior.`interiors.csv` values(14,'True Indian','Office Table','28-03-2003',15000,20);
Select Count(DISTINCT TYPE) from interior.`interiors.csv`;
Select AVG(DISCOUNT) from interior.`interiors.csv` where TYPE='BABY COT';
Select SUM(PRICE) from interior.`interiors.csv` where `DATE OF STOCK`<'12-02-2002';
Select * from interior.`interiors.csv`;
Alter TABLE interior.`interiors.csv` ADD `QUANTITY` int;
Alter TABLE interior.`interiors.csv` drop column `QUANTITY`;  
Alter TABLE interior.`interiors.csv` modify column `PRICE` float;
Select distinct `TYPE` from interior.`interiors.csv`;
Select * from interior.`interiors.csv` where TYPE='Baby Cot';
Select * from interior.`interiors.csv` where TYPE='Baby Cot' AND PRICE=9000;
Select * from interior.`interiors.csv` where TYPE='Baby Cot' OR PRICE=9000;
Select * from interior.`interiors.csv` where PRICE BETWEEN 8500 AND 16000;
Select * from interior.`interiors.csv` where PRICE NOT BETWEEN 8500 AND 16000;
Select AVG(PRICE) from interior.`interiors.csv`;
Select COUNT(*) from interior.`interiors.csv`;
Select SUM(PRICE) from interior.`interiors.csv`;
Select MAX(PRICE) from interior.`interiors.csv`;
Select MIN(PRICE) from interior.`interiors.csv`;